add sidebar
ncedu-tlt/2021-ux-heartbeat pull request #22
Opened 2022-02-18 15:55 UTC by LMikhail163

add sidebar

2022-02-20 08:51 UTC, Nikel163 commented on src/app/components/sidebar/sidebar.component.css
> +.navigation {
мы используем less, поэтому css файл не нужен

2022-02-20 08:53 UTC, Nikel163 commented on src/app/app.component.html
> +<!-- <nz-layout class="app-layout">
тут оставь прежний вариант, данный компонент будет использовать при составлении базовой страницы в рамках #17

2022-02-20 09:13 UTC, LMikhail163 commented
Исправил

2022-02-20 09:15 UTC, Nikel163 commented on src/app/components/sidebar/sidebar.component.css
> +.navigation {
тут ещё не удалил файл

2022-02-20 09:16 UTC, Nikel163 commented on src/app/components/sidebar/sidebar.component.css
> +.navigation {
отмена, смотрел старую версию

2022-02-20 09:18 UTC, Nikel163 submitted a review, later dismissed

2022-02-21 07:58 UTC, ocassio requested changes

2022-02-21 07:58 UTC, ocassio commented on src/app/app.module.ts
> +  declarations: [AppComponent, SidebarComponent],
А где использование компонента?

2022-02-21 07:58 UTC, ocassio commented on src/app/components/sidebar/sidebar.component.less
> +   background-color: #F2F4F9;
Цвета давай выносить в отдельный файл `colors.less`. Они по-любому будут переиспользоваться.  
Ну и остальные истории, где ты такое видишь. Например, часто выносят миксины на шрифты.

2022-02-21 07:59 UTC, Nikel163 commented on src/app/app.module.ts
> +  declarations: [AppComponent, SidebarComponent],
использование будет при #17

2022-02-21 08:00 UTC, ocassio commented on src/app/app.component.html
> +<!-- <nz-layout class="app-layout">
Пусть используется, это же все равно заглушка временная. Зато пощупать можно.

2022-02-22 14:26 UTC, LMikhail163 commented
Добавил color.less

2022-02-23 20:24 UTC, Nikel163 approved these changes, later dismissed

2022-02-23 21:13 UTC, Nikel163 requested changes
замечания отписаны в лс

2022-02-26 18:21 UTC, Nikel163 commented on src/app/components/sidebar/sidebar.component.less
> +@import '../../../assets/styles/color.less';
перенеси импорт наверх

2022-02-26 18:21 UTC, Nikel163 submitted a review, later dismissed
Саш, взгляни. Для меня мерж ок

2022-02-28 07:56 UTC, ocassio requested changes

2022-02-28 07:56 UTC, ocassio commented on src/assets/styles/color.less
> +@background-color: #F2F4F9;
Название файла должно быть colors, а не color. Их же тут будет много :)

2022-02-28 07:56 UTC, ocassio commented
И сделай мерж из мастера, там явно должны быть конфликты.

2022-02-28 07:57 UTC, Nikel163 commented
> 

мерж был, конфликты уже зарезолвили

2022-02-28 14:44 UTC, ocassio approved these changes

2022-02-28 14:44 UTC, merged