Feature/9-player
ncedu-tlt/2021-ux-heartbeat pull request #23
Opened 2022-02-21 11:45 UTC by AntoninaTrapsh

2022-02-21 16:23 UTC, ocassio requested changes
Сейчас функционал на мобилке урезан в сравнении с десктопной версией, такого быть не должно.

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.html
> +          {{musicCurrentTime$.getValue() | timeFormat}}
Почему getValue вместо async pipe?

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.less
> +  background: #F7F9FE;
Цвет выносим в константы в colors.less. Они будут переиспользоваться.

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +  private stop$: Subject<any> = new Subject();
Почему any?

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +  public musicVolume$ = new BehaviorSubject<number | null>(100);
При каких условиях там может быть null?

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +  public currentPositionTooltip: NgStyleInterface = { left: "-18px" };
currentTooltipPosition

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +  changePlayerState(): void {
Слишком абстрактное имя функции.

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    if (this.player != undefined) {
`!this.player` будет лучше, если ты конечно, не специально сверяешь исключительно с `undefined`.

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    this.displayScaleProgress((this.player as HTMLAudioElement).currentTime);
Четыре раза приведение типа для плеера делаешь. Сделай один раз, запиши результат и используй.

2022-02-21 16:23 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    this.musicVolume$.next((this.player?.volume as number) * 100);
Код по факту не рассчитывает на то, что player может отсутствовать. Причем по всему классу. Если ты уверена, что по факту он всегда будет инициализирован, то используй такую историю:  
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions

2022-02-21 16:23 UTC, ocassio commented on src/app/pipes/time-format.pipe.ts
> +export class FormatPipe implements PipeTransform {
TimeFormatPipe тогда уж.

2022-02-21 16:23 UTC, ocassio commented on src/app/services/player.service.ts
> +  getTrack(trackInfo: PlayerTrackInfoModel) {
Выглядит как set, а не get.

2022-02-21 16:23 UTC, ocassio commented on src/styles.less
> +}
Уверена, что ты хочешь отключить это везде, а не только в плеере?

2022-02-22 06:28 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.html
> +          {{musicCurrentTime$.getValue() | timeFormat}}
Сначала использовала async pipe, но подумала, что если это BehaviorSubject, то можно просто getValue оставить. Мне показалось, что это будет равнозначно

2022-02-22 06:29 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.ts
> +  private stop$: Subject<any> = new Subject();
Следовала логике, что этот Subject создан только для отписки и нам, наверное, не прицнипиально важно, что туда передавать через next

2022-02-22 06:30 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.ts
> +  public musicVolume$ = new BehaviorSubject<number | null>(100);
Ни при каких, сглупила

2022-02-22 06:31 UTC, AntoninaTrapsh commented on src/styles.less
> +}
Изначально планировалось отключить только в компоненте плеера, но почему-то если прописываю там, то стили не задаются

2022-02-22 06:31 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.ts
> +    this.musicVolume$.next((this.player?.volume as number) * 100);
Хорошо, исправлю

2022-02-22 07:03 UTC, ocassio commented on src/app/components/player/player.component.ts
> +  private stop$: Subject<any> = new Subject();
В этом случае надо вообще ничего не передавать и объявить тип как Subject<void>.

2022-02-22 07:04 UTC, ocassio commented on src/app/components/player/player.component.html
> +          {{musicCurrentTime$.getValue() | timeFormat}}
getValue получает значение в момент отрисовки, но не подписывается на его изменение. Соответственно, в некоторых случаях, значение может не обновиться на UI.

2022-02-22 07:18 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.html
> +          {{musicCurrentTime$.getValue() | timeFormat}}
Хорошо, исправлю

2022-02-22 11:55 UTC, AntoninaTrapsh commented on src/styles.less
> +}
А, все, нашла решение проблемы

2022-02-22 16:56 UTC, AntoninaTrapsh commented
Исправила

2022-02-23 20:48 UTC, AntoninaTrapsh commented
Добавлено развертывание полного функционала в мобильной версии, исправлены замечания, логика плеера перенесена в сервис.

2022-02-25 18:11 UTC, ocassio requested changes

2022-02-25 18:11 UTC, ocassio commented on src/app/services/player.service.ts
> +    this.player.loop = !this.player?.loop;
Остался optional chaining в нескольких местах.

2022-02-25 18:11 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    window.addEventListener("resize", () => {
Не вижу отписку.

2022-02-25 18:11 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    this.playerService.createAudioElement();
Может вызваться дважды, сервис к такому готов?

2022-02-25 18:42 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.ts
> +    this.playerService.createAudioElement();
А в каких случаях он может вызваться дважды? Не совсем понимаю

2022-02-25 19:46 UTC, ocassio commented on src/app/components/player/player.component.ts
> +    this.playerService.createAudioElement();
Если компонент будет пересоздан.

2022-02-25 20:22 UTC, AntoninaTrapsh commented
Исправила

2022-02-25 20:43 UTC, ocassio approved these changes

2022-02-25 20:43 UTC, merged