Feature/14 playlist page/albums page
ncedu-tlt/2021-ux-heartbeat pull request #51
Opened 2022-03-20 19:15 UTC by AlexFGeeR

2022-03-21 07:40 UTC, Nikel163 requested changes

2022-03-21 07:40 UTC, Nikel163 commented on src/app/pages/albums-page/albums-page.component.ts
> +    this.isLoading = false;
перенести в subscribe

2022-03-21 07:50 UTC, ocassio requested changes

2022-03-21 07:50 UTC, ocassio commented on src/app/models/new-api-models/album-by-id.model.ts
> +export interface ItemsAlbumContain {
Почему не просто Album?

2022-03-21 07:50 UTC, ocassio commented on src/app/models/new-api-models/album-by-id.model.ts
> +export interface ItemsAlbumsContain {
AlbumItem?

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.html
> +          <div class="selected-album__img" [ngStyle]="{'width': '150px','height': '150px','border-radius': '5px','background-image': 'url(' + albumImage[0].url + ')', 'background-position': 'center',
Не многовато inline стилей? Вычисляется то только `background-image`.

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.html
> +      <div *ngFor="let album of albums" id="{{album.album.id}}" (click)="openAlbum(album.album.id, album.album.images, album.album.name, album.album.artists[0].name)" class="album">
А не проще весь альбом передать?

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.less
> +      }
Давай везде без пробелов у скобок писать.

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.less
> +            background-color: #C4C4C430;
Цвета в константы.

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.ts
> +  public albumArtists = "";
Мне кажется, что проще весь альбом тут держать.

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/albums-page/albums-page.component.ts
> +  }
Почему тут прямое взаимодействие с DOM?

2022-03-21 07:50 UTC, ocassio commented on src/app/pages/playlists-page/playlists-page.component.html
> +      <div *ngFor="let playlist of playlists" id="{{playlist.id}}" (click)="openPlaylist(playlist.id, playlist.images[0].url, playlist.owner.display_name, playlist.name)" class="playlist">
Та же история, что с альбомом.

2022-03-23 13:24 UTC, AlexFGeeR commented
Внес необходимые правки.

2022-03-24 14:20 UTC, Nikel163 submitted a review, later dismissed

2022-03-24 14:34 UTC, Nikel163 commented on src/app/pages/albums-page/albums-page.component.less
> +@album-background: #C4C4C430;
вынести цвет в colors.less

2022-03-24 14:35 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.less
> +@playlist-background: #C4C4C430;
вынести цвет в colors.less

2022-03-25 06:40 UTC, ocassio approved these changes, later dismissed

2022-03-27 18:09 UTC, Nikel163 approved these changes

2022-03-28 06:58 UTC, ocassio approved these changes

2022-03-28 06:58 UTC, Nikel163 approved these changes

2022-03-28 06:59 UTC, merged