Feature/49 player v3
ncedu-tlt/2021-ux-heartbeat pull request #54
Opened 2022-03-28 08:53 UTC by AntoninaTrapsh

2022-03-28 13:16 UTC, Nikel163 requested changes

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +            <span *ngIf="i">, </span>
в каком случае тут не будет индекса?

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +      <button class="player__no-repeat" *ngIf="playerService.isRepeat === 0"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +      <button class="player__repeat" *ngIf="playerService.isRepeat === 1"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +      <button class="player__repeat" *ngIf="playerService.isRepeat === 2"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +          <button class="mobile-player-contain__no-repeat" *ngIf="playerService.isRepeat === 0"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +          <button class="mobile-player-contain__repeat" *ngIf="playerService.isRepeat === 1"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +          <button class="player__repeat" *ngIf="playerService.isRepeat === 2"
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.ts
> +  @ViewChild("artistNames") mobileArtistNameLine!: ElementRef;
уточнить тип, например ElementRef<HTMLDivElement>

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.ts
> +              this.mobileArtistNameLine.nativeElement as HTMLElement
убрать каст после уточнения типа на 30 строке

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.ts
> +          this.mobileArtistNameLine.nativeElement as HTMLElement
убрать каст после уточнения типа на 30 строке

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.ts
> +    this.movingLineScrollWidth = (e?.currentTarget as HTMLElement).scrollWidth;
e?.currentTarget - убрать вопросительный знак, т.к. иф выше гарантирует, что e не равен null

2022-03-28 13:16 UTC, Nikel163 commented on src/app/components/player/player.component.ts
> +    if (this.movingLineScrollWidth > blockWidth) {
инвертировать условие
`if (this.movingLineScrollWidth < blockWidth) {
    return;
}`

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +type trackList =
тип с большой буквы

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +type track = TrackById | NewAlbumTracksModel | TopTracksModel;
тип с большой буквы

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +  public isRepeat = 0;
использовать енам вместо 0/1/2

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +        if (isShuffle) {
`if (isShuffle && this.trackList$.getValue())` ?

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +          if (this.trackList$.getValue()?.items) {
если отсюда убрать else и просто оставить ниже if (this.trackList$.getValue()?.items), то есть вероятность того, что выполнится сразу два условия if (isShuffle && this.trackList$.getValue()) и if (this.trackList$.getValue()?.items)?

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +    if (this.player.currentTime === this.player.duration) {
if (this.player.currentTime === this.player.duration && !this.player.loop)

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +    if (!this.isRepeat) {
if (!this.isRepeat && this.player.currentTime === this.player.duration)

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +    if (this.isRepeat === 1) {
использовать енам

2022-03-28 13:16 UTC, Nikel163 commented on src/app/services/player.service.ts
> +    if (this.isShuffle$.getValue()) {
return this.isShuffle$.getValue()
    ? this.shuffleTrackList.items[index]?.track
    : this.trackList$.getValue()?.items[index]?.track;

2022-03-28 13:36 UTC, AntoninaTrapsh commented on src/app/components/player/player.component.html
> +            <span *ngIf="i">, </span>
условие написано для того, чтобы запятая не отрисовывалась перед элементом с индексом 0

2022-03-29 11:05 UTC, Nikel163 approved these changes

2022-03-29 11:09 UTC, Nikel163 approved these changes

2022-03-29 11:10 UTC, merged