Features/59 improve playlist page
ncedu-tlt/2021-ux-heartbeat pull request #71
Opened 2022-04-16 20:05 UTC by AntoninaTrapsh

2022-04-18 09:55 UTC, Nikel163 requested changes

2022-04-18 09:55 UTC, Nikel163 commented on src/app/components/player/player.component.html
> +          <div class="mobile-player-contain__mixing" *ngIf="!player.isShuffle"
- можно объединить два дива в один, а стили выбирать при помощи ngClass
![image](https://user-images.githubusercontent.com/33506510/163774595-83843beb-8b3a-4eaf-8a03-80c51fc2d7b8.png)
- клик упрощается до .next(!player.isShuffle)

2022-04-18 09:55 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.ts
> +    if (!(file.type === "image/jpeg" || file.type === "image/png")) {
раскрыть скобки: file.type !== "..." || file.type !== "..."
увеличение скобок затрудняет понимание кода

2022-04-18 09:55 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.ts
> +      this.fileWarning = "Размер файла не должен превышать 150КБ";
чем обусловлено такое ограничение?

2022-04-18 09:55 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.ts
> +    if (playlistImage) {
if (!playlistImage) {
return of();
}

return ....

2022-04-18 09:55 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.ts
> +  ): Observable<void | null> {
Observable < void >

2022-04-18 09:55 UTC, Nikel163 commented on src/app/pages/playlists-page/playlists-page.component.ts
> +  removePlaylistImg() {
: void

2022-04-18 10:07 UTC, AntoninaTrapsh commented on src/app/pages/playlists-page/playlists-page.component.ts
> +      this.fileWarning = "Размер файла не должен превышать 150КБ";
У спотифая на эту апи нет документации. Опытным путем удалось установить, что если файл весит более 150Кб, то спотифай возвращает ошибку 413.

2022-04-18 11:07 UTC, AntoninaTrapsh commented on src/app/pages/playlists-page/playlists-page.component.ts
> +  ): Observable<void | null> {
![image](https://user-images.githubusercontent.com/82774971/163799916-19810572-6105-413f-b7e6-afae40e6e36f.png)

2022-04-18 11:10 UTC, AntoninaTrapsh commented on src/app/pages/playlists-page/playlists-page.component.ts
> +  ): Observable<void | null> {
Уже пробовала возвращать там of() вместо of(null), у меня после этого некорректно вызов в changePlaylistInformation отрабатывал.

2022-04-19 06:25 UTC, Nikel163 approved these changes, later dismissed

2022-04-19 06:27 UTC, Nikel163 commented
надо порешать конфликты

2022-04-19 12:26 UTC, Nikel163 approved these changes

2022-04-19 12:26 UTC, merged